# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "breeding_since",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rok, od kdy chovatel chová",
                        null=True,
                        verbose_name="Chov od",
                    ),
                ),
                (
                    "other_species",
                    models.CharField(
                        blank=True,
                        help_text="Např. papoušci, holubi apod.",
                        max_length=255,
                        null=True,
                        verbose_name="Další druhy",
                    ),
                ),
                (
                    "has_offspring",
                    models.BooleanField(
                        default=False,
                        help_text="Zda chovatel má odchovy",
                        verbose_name="Má odchovy",
                    ),
                ),
                (
                    "participates_in_projects",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Zda chovatel spolupracuje na projektech",
                        verbose_name="Zapojen v projektech",
                    ),
                ),
                (
                    "cooperates",
                    models.BooleanField(
                        default=False,
                        help_text="Zda chovatel spolupracuje s ostatními chovateli",
                        verbose_name="Spolupracuje s chovateli",
                    ),
                ),
                (
                    "allows_visits",
                    models.BooleanField(
                        default=False,
                        help_text="Zda chovatel umožňuje návštěvy",
                        verbose_name="Možnost návštěvy",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Jméno zobrazené na veřejném profilu",
                        max_length=150,
                        null=True,
                        verbose_name="Zobrazované jméno",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Krátké představení chovatele",
                        null=True,
                        verbose_name="Bio",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Nahraná profilová fotografie",
                        null=True,
                        upload_to="profiles/avatars/",
                        verbose_name="Profilová fotka",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Město nebo oblast",
                        max_length=150,
                        null=True,
                        verbose_name="Lokalita",
                    ),
                ),
                (
                    "public_email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="E-mail zobrazený na profilu",
                        max_length=254,
                        null=True,
                        verbose_name="Veřejný e-mail",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefonní číslo v mezinárodním formátu",
                        max_length=50,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(7)],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na webové stránky",
                        null=True,
                        verbose_name="Web",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na Facebook profil",
                        null=True,
                        verbose_name="Facebook",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na Instagram profil",
                        null=True,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na YouTube kanál",
                        null=True,
                        verbose_name="YouTube",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Zda je profil veřejně viditelný",
                        verbose_name="Veřejný profil",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False,
                        help_text="Zobrazit e-mail na profilu",
                        verbose_name="Zobrazit e-mail",
                    ),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Zobrazit telefon na profilu",
                        verbose_name="Zobrazit telefon",
                    ),
                ),
                (
                    "show_location",
                    models.BooleanField(
                        default=True,
                        help_text="Zobrazit lokalitu",
                        verbose_name="Zobrazit lokalitu",
                    ),
                ),
                (
                    "show_website",
                    models.BooleanField(
                        default=False,
                        help_text="Zobrazit web na profilu",
                        verbose_name="Zobrazit web",
                    ),
                ),
                (
                    "show_social",
                    models.BooleanField(
                        default=True,
                        help_text="Zobrazit odkazy na sociální sítě",
                        verbose_name="Zobrazit sociální sítě",
                    ),
                ),
                (
                    "show_bio",
                    models.BooleanField(
                        default=True,
                        help_text="Zobrazit bio na profilu",
                        verbose_name="Zobrazit bio",
                    ),
                ),
                (
                    "show_gallery",
                    models.BooleanField(
                        default=True,
                        help_text="Zobrazit galerii na profilu",
                        verbose_name="Zobrazit galerii",
                    ),
                ),
                (
                    "show_videos",
                    models.BooleanField(
                        default=True,
                        help_text="Zobrazit videa na profilu",
                        verbose_name="Zobrazit videa",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky (neveřejné)",
                        null=True,
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        help_text="Vazba na členský profil",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_profile",
                        to="members.memberprofile",
                        verbose_name="Člen",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Druhy, které člen chová",
                        related_name="public_profiles",
                        to="taxonomy.species",
                        verbose_name="Chované druhy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veřejný profil",
                "verbose_name_plural": "Veřejné profily",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Odkaz na YouTube video nebo kanál",
                        verbose_name="YouTube URL",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Volitelný název videa",
                        max_length=255,
                        null=True,
                        verbose_name="Název",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="profiles.publicprofile",
                        verbose_name="Profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video profilu",
                "verbose_name_plural": "Videa profilů",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="profiles/gallery/", verbose_name="Obrázek"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Volitelný popis fotografie",
                        max_length=255,
                        null=True,
                        verbose_name="Popis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="profiles.publicprofile",
                        verbose_name="Profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografie galerie",
                "verbose_name_plural": "Galerie profilu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["display_name"], name="profiles_pu_display_6225b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["location"], name="profiles_pu_locatio_0e5e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["is_public"], name="profiles_pu_is_publ_a1d34c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["breeding_since"], name="profiles_pu_breedin_937dc4_idx"
            ),
        ),
    ]
