# Generated by Django 6.0.3 on 2026-04-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/avatars/"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("specialization", models.CharField(blank=True, max_length=255)),
                ("breeding_focus", models.TextField(blank=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_location", models.BooleanField(default=True)),
                ("show_breeding", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_profile",
                        to="members.memberprofile",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        related_name="public_profiles",
                        to="taxonomy.species",
                        verbose_name="Chované druhy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veřejný profil",
                "verbose_name_plural": "Veřejné profily",
            },
        ),
    ]
