# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0003_alter_memberprofile_city_alter_memberprofile_country_and_more",
        ),
        ("profiles", "0001_initial"),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Veřejný profil",
                "verbose_name_plural": "Veřejné profily",
            },
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Nahraná profilová fotografie",
                null=True,
                upload_to="profiles/avatars/",
                verbose_name="Profilová fotka",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Krátké představení chovatele", verbose_name="Bio"
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="breeding_focus",
            field=models.TextField(
                blank=True,
                help_text="Detailní popis chovu",
                verbose_name="Chovatelské zaměření",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Jméno zobrazené na veřejném profilu",
                max_length=150,
                verbose_name="Zobrazované jméno",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                help_text="Odkaz na Facebook profil",
                verbose_name="Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Zda je profil veřejně viditelný",
                verbose_name="Veřejný profil",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="location",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Město nebo oblast",
                max_length=150,
                verbose_name="Lokalita",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="member",
            field=models.OneToOneField(
                help_text="Vazba na členský profil",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_profile",
                to="members.memberprofile",
                verbose_name="Člen",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Interní poznámky (neveřejné)",
                verbose_name="Poznámky",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Telefonní číslo v mezinárodním formátu",
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(7)],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="public_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="E-mail zobrazený na profilu",
                max_length=254,
                verbose_name="Veřejný e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="show_breeding",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit chovatelské informace",
                verbose_name="Zobrazit chov",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="show_email",
            field=models.BooleanField(
                default=False,
                help_text="Zobrazit e-mail na profilu",
                verbose_name="Zobrazit e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="show_location",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit lokalitu",
                verbose_name="Zobrazit lokalitu",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="show_phone",
            field=models.BooleanField(
                default=False,
                help_text="Zobrazit telefon na profilu",
                verbose_name="Zobrazit telefon",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="Na co se chovatel zaměřuje",
                max_length=255,
                verbose_name="Specializace",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                help_text="Druhy, které člen chová",
                related_name="public_profiles",
                to="taxonomy.species",
                verbose_name="Chované druhy",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="website",
            field=models.URLField(
                blank=True, help_text="Odkaz na webové stránky", verbose_name="Web"
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Počet let zkušeností s chovem",
                null=True,
                verbose_name="Roky zkušeností",
            ),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="Odkaz na YouTube kanál", verbose_name="YouTube"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["display_name"], name="profiles_pu_display_6225b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["location"], name="profiles_pu_locatio_0e5e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicprofile",
            index=models.Index(
                fields=["is_public"], name="profiles_pu_is_publ_a1d34c_idx"
            ),
        ),
    ]
