# Generated by Django 6.0.3 on 2026-04-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="publicprofile",
            name="profiles_pu_breedin_937dc4_idx",
        ),
        migrations.AddField(
            model_name="publicprofile",
            name="public_info",
            field=models.TextField(
                blank=True,
                help_text="Text zobrazený na veřejném profilu (např. informace o chovu, zkušenosti apod.)",
                null=True,
                verbose_name="Veřejné informace",
            ),
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="breeding_since",
        ),
    ]
