# Generated by Django 6.0.3 on 2026-04-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_remove_publicprofile_profiles_pu_breedin_937dc4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publicprofile",
            name="show_avatar",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit profilovou fotku",
                verbose_name="Zobrazit avatar",
            ),
        ),
        migrations.AddField(
            model_name="publicprofile",
            name="show_info",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit veřejné informace",
                verbose_name="Zobrazit informace",
            ),
        ),
        migrations.AddField(
            model_name="publicprofile",
            name="show_species",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit chované druhy",
                verbose_name="Zobrazit druhy",
            ),
        ),
    ]
