# Generated by Django 6.0.3 on 2026-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_publicprofile_show_avatar_publicprofile_show_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilegallery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fotografie",
                "verbose_name_plural": "Galerie",
            },
        ),
        migrations.AlterModelOptions(
            name="profilevideo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videa",
            },
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Informace o chovateli (zobrazené na veřejném profilu)",
                null=True,
                verbose_name="O chovateli",
            ),
        ),
    ]
