# Generated by Django 6.0.3 on 2026-04-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profilegallery_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="publicprofile",
            name="profiles_pu_locatio_0e5e1b_idx",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="location",
        ),
    ]
