# Generated by Django 6.0.3 on 2026-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0005_remove_publicprofile_profiles_pu_locatio_0e5e1b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publicprofile",
            name="show_other_species",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit pole 'další druhy'",
                verbose_name="Zobrazit další druhy",
            ),
        ),
    ]
