# Generated by Django 6.0.3 on 2026-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_publicprofile_show_other_species"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicprofile",
            name="allows_visits",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="cooperates",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="has_offspring",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="participates_in_projects",
        ),
        migrations.RemoveField(
            model_name="publicprofile",
            name="public_info",
        ),
        migrations.AddField(
            model_name="publicprofile",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="Další informace o chovu, zkušenosti, poznámky apod.",
                null=True,
                verbose_name="Doplňující informace",
            ),
        ),
    ]
