# Generated by Django 6.0.3 on 2026-04-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_publicprofile_allows_visits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicprofile",
            name="show_info",
        ),
        migrations.AddField(
            model_name="publicprofile",
            name="show_additional_info",
            field=models.BooleanField(
                default=True,
                help_text="Zobrazit sekci doplňujících informací",
                verbose_name="Zobrazit doplňující informace",
            ),
        ),
    ]
