# Generated by Django 6.0.3 on 2026-04-18 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_remove_publicprofile_show_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilegallery",
            name="caption",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Volitelný popis fotografie",
                max_length=255,
                verbose_name="Popis",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profilevideo",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Volitelný název videa",
                max_length=255,
                verbose_name="Název",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="additional_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Další informace o chovu, zkušenosti, poznámky apod.",
                verbose_name="Doplňující informace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Informace o chovateli (zobrazené na veřejném profilu)",
                verbose_name="O chovateli",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Jméno zobrazené na veřejném profilu",
                max_length=150,
                verbose_name="Zobrazované jméno",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Odkaz na Facebook profil",
                verbose_name="Facebook",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Odkaz na Instagram profil",
                verbose_name="Instagram",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Interní poznámky (neveřejné)",
                verbose_name="Poznámky",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="other_species",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Např. papoušci, holubi apod.",
                max_length=255,
                verbose_name="Další druhy",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Telefonní číslo v mezinárodním formátu",
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(7)],
                verbose_name="Telefon",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="public_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                default="",
                help_text="E-mail zobrazený na profilu",
                max_length=254,
                verbose_name="Veřejný e-mail",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Odkaz na webové stránky",
                verbose_name="Web",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Odkaz na YouTube kanál",
                verbose_name="YouTube",
            ),
            preserve_default=False,
        ),
    ]
