# Generated by Django 6.0.3 on 2026-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profilegallery_caption_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilegallery",
            options={
                "ordering": ["-is_primary", "-created_at"],
                "verbose_name": "Fotografie",
                "verbose_name_plural": "Galerie",
            },
        ),
        migrations.AddField(
            model_name="profilegallery",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Označit jako hlavní profilovou fotografii",
                verbose_name="Hlavní fotografie",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilegallery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="unique_primary_image_per_profile",
            ),
        ),
    ]
