# Generated by Django 6.0.3 on 2026-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Uživatel",
                "verbose_name_plural": "Uživatelé",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření účtu",
                verbose_name="Datum registrace",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Unikátní e-mail uživatele",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Zda byl e-mail uživatele ověřen",
                verbose_name="E-mail ověřen",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Křestní jméno", max_length=64, verbose_name="Jméno"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Zda je uživatelský účet aktivní",
                verbose_name="Aktivní",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Zda má uživatel přístup do administrace",
                verbose_name="Administrátor",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Příjmení", max_length=64, verbose_name="Příjmení"
            ),
        ),
    ]
