# Generated by Django 5.2.4 on 2026-04-02 17:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user's email has been verified.",
                verbose_name="Email Verified",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when the user registered.",
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indicates whether the user account is active.",
                verbose_name="Active User",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="user_email_lower_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="accounts_user",
        ),
    ]
