# Generated by Django 6.0.3 on 2026-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Název události nebo akce.",
                        max_length=255,
                        verbose_name="Název akce",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unikátní URL identifikátor události.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailní popis události.",
                        verbose_name="Popis",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("cz_sk", "WPA CZ-SK"),
                            ("de", "WPA Deutschland"),
                            ("uk", "WPA UK"),
                            ("at", "WPA Austria"),
                            ("benelux", "WPA Benelux"),
                            ("fr", "WPA France"),
                            ("other", "Jiná sekce"),
                        ],
                        db_index=True,
                        default="cz_sk",
                        help_text="Sekce WPA, ze které událost pochází.",
                        max_length=20,
                        verbose_name="Sekce WPA",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Datum a čas začátku události.",
                        verbose_name="Začátek",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Datum a čas ukončení události.",
                        null=True,
                        verbose_name="Konec",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Místo konání události.",
                        max_length=255,
                        verbose_name="Místo",
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Organizátor nebo pořadatel události.",
                        max_length=255,
                        verbose_name="Organizátor",
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=False,
                        help_text="Určuje, zda je událost převzatá z jiné WPA sekce.",
                        verbose_name="Externí",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na originální stránku události.",
                        verbose_name="Zdrojová URL",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na registraci nebo detail akce.",
                        verbose_name="Externí odkaz",
                    ),
                ),
                (
                    "itinerary",
                    models.TextField(
                        blank=True,
                        help_text="Detailní program události, harmonogram nebo plán průběhu.",
                        verbose_name="Program / itinerář",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k události.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, zda se má událost zobrazit veřejně.",
                        verbose_name="Veřejná",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Zvýrazněná událost, například na homepage.",
                        verbose_name="Doporučená",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Druhy, kterých se událost týká.",
                        related_name="events",
                        to="taxonomy.species",
                        verbose_name="Související druhy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Událost",
                "verbose_name_plural": "Události",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="events_even_start_d_d4b514_idx"
                    ),
                    models.Index(
                        fields=["section"], name="events_even_section_fc39fb_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="events_even_is_publ_e2e10e_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="events_even_is_feat_765082_idx"
                    ),
                ],
            },
        ),
    ]
