# Generated by Django 6.0.3 on 2026-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Datum a čas ukončení události.",
                null=True,
                verbose_name="Konec",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Zvýrazněná událost, například na homepage.",
                verbose_name="Doporučená",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Určuje, zda se má událost zobrazit veřejně.",
                verbose_name="Veřejná",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Místo konání události.",
                max_length=255,
                verbose_name="Místo",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Organizátor nebo pořadatel události.",
                max_length=255,
                verbose_name="Organizátor",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date"], name="events_even_start_d_d4b514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["section"], name="events_even_section_fc39fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_public"], name="events_even_is_publ_e2e10e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_featured"], name="events_even_is_feat_765082_idx"
            ),
        ),
    ]
