# Generated by Django 6.0.3 on 2026-04-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Autor"),
                            ("photographer", "Fotograf"),
                            ("translator", "Překladatel"),
                            ("other", "Jiné"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to="members.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Přispěvatel",
                "verbose_name_plural": "Přispěvatelé",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="articles/pdf/"),
                ),
                ("pdf_title", models.CharField(blank=True, max_length=255)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/images/"
                    ),
                ),
                ("publication_date", models.DateField(db_index=True)),
                ("published_in", models.CharField(blank=True, max_length=255)),
                ("published_in_date", models.DateField(blank=True, null=True)),
                ("published_in_url", models.URLField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "related_articles",
                    models.ManyToManyField(blank=True, to="articles.article"),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="taxonomy.species"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="articles.category",
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="articles.contributor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Článek",
                "verbose_name_plural": "Články",
                "ordering": ["-publication_date"],
            },
        ),
    ]
