# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Název kategorie",
                        max_length=100,
                        verbose_name="Název",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Pořadí zobrazení (nižší = dříve)",
                        verbose_name="Pořadí",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Jméno přispěvatele (pokud není člen)",
                        max_length=150,
                        verbose_name="Jméno",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Autor"),
                            ("photographer", "Fotograf"),
                            ("translator", "Překladatel"),
                            ("other", "Jiné"),
                        ],
                        db_index=True,
                        help_text="Role přispěvatele u článku",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Přispěvatel",
                "verbose_name_plural": "Přispěvatelé",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, zda je záznam veřejně viditelný",
                        verbose_name="Publikováno",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas publikace",
                        null=True,
                        verbose_name="Publikováno dne",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Název článku",
                        max_length=200,
                        verbose_name="Titulek",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Krátké shrnutí článku",
                        verbose_name="Shrnutí",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Volitelný PDF soubor článku",
                        null=True,
                        upload_to="articles/pdf/",
                        verbose_name="PDF soubor",
                    ),
                ),
                (
                    "pdf_title",
                    models.CharField(
                        blank=True,
                        help_text="Popis nebo název PDF souboru",
                        max_length=255,
                        verbose_name="Název PDF",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hlavní ilustrační obrázek článku",
                        null=True,
                        upload_to="articles/images/",
                        verbose_name="Hlavní obrázek",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        db_index=True,
                        help_text="Datum publikace článku",
                        verbose_name="Datum publikace",
                    ),
                ),
                (
                    "published_in",
                    models.CharField(
                        blank=True,
                        help_text="Název publikace nebo zdroje",
                        max_length=255,
                        verbose_name="Publikováno v",
                    ),
                ),
                (
                    "published_in_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum vydání v externím zdroji",
                        null=True,
                        verbose_name="Datum vydání",
                    ),
                ),
                (
                    "published_in_url",
                    models.URLField(
                        blank=True,
                        help_text="Externí odkaz na publikovaný článek",
                        verbose_name="Odkaz na zdroj",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámka",
                        verbose_name="Poznámka",
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Další související obsah",
                        to="articles.article",
                        verbose_name="Související články",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Související druhy",
                        related_name="articles",
                        to="taxonomy.species",
                        verbose_name="Druhy",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Kategorie článku",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="articles.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Článek",
                "verbose_name_plural": "Články",
                "ordering": ["-publication_date"],
            },
        ),
    ]
