# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Odkaz na člena, pokud je přispěvatelem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="members.memberprofile",
                verbose_name="Člen",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Autoři, fotografové a další",
                related_name="articles",
                to="articles.contributor",
                verbose_name="Přispěvatelé",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["publication_date"], name="articles_ar_publica_044c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category"], name="articles_ar_categor_ef2274_idx"
            ),
        ),
    ]
