# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        (
            "members",
            "0003_alter_memberprofile_city_alter_memberprofile_country_and_more",
        ),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                help_text="Kategorie článku",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="articles.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Autoři, fotografové a další",
                related_name="articles",
                to="articles.contributor",
                verbose_name="Přispěvatelé",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Určuje, zda je záznam veřejně viditelný",
                verbose_name="Publikováno",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Hlavní ilustrační obrázek článku",
                null=True,
                upload_to="articles/images/",
                verbose_name="Hlavní obrázek",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="note",
            field=models.TextField(
                blank=True, help_text="Interní poznámka", verbose_name="Poznámka"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Volitelný PDF soubor článku",
                null=True,
                upload_to="articles/pdf/",
                verbose_name="PDF soubor",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_title",
            field=models.CharField(
                blank=True,
                help_text="Popis nebo název PDF souboru",
                max_length=255,
                verbose_name="Název PDF",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateField(
                db_index=True,
                help_text="Datum publikace článku",
                verbose_name="Datum publikace",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum a čas publikace",
                null=True,
                verbose_name="Publikováno dne",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_in",
            field=models.CharField(
                blank=True,
                help_text="Název publikace nebo zdroje",
                max_length=255,
                verbose_name="Publikováno v",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_in_date",
            field=models.DateField(
                blank=True,
                help_text="Datum vydání v externím zdroji",
                null=True,
                verbose_name="Datum vydání",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_in_url",
            field=models.URLField(
                blank=True,
                help_text="Externí odkaz na publikovaný článek",
                verbose_name="Odkaz na zdroj",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Další související obsah",
                to="articles.article",
                verbose_name="Související články",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                help_text="Související druhy",
                related_name="articles",
                to="taxonomy.species",
                verbose_name="Druhy",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Krátké shrnutí článku", verbose_name="Shrnutí"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Název článku",
                max_length=200,
                verbose_name="Titulek",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Název kategorie",
                max_length=100,
                verbose_name="Název",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Pořadí zobrazení (nižší = dříve)",
                verbose_name="Pořadí",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="Odkaz na člena, pokud je přispěvatelem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to="members.memberprofile",
                verbose_name="Člen",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Jméno přispěvatele (pokud není člen)",
                max_length=150,
                verbose_name="Jméno",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Autor"),
                    ("photographer", "Fotograf"),
                    ("translator", "Překladatel"),
                    ("other", "Jiné"),
                ],
                db_index=True,
                help_text="Role přispěvatele u článku",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["publication_date"], name="articles_ar_publica_044c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category"], name="articles_ar_categor_ef2274_idx"
            ),
        ),
    ]
