# Generated by Django 5.1.5 on 2025-02-06 19:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the user registered.",
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="User's unique email address.",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="User's first name.", max_length=64, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    models.F("first_name"), models.Value(" "), models.F("last_name")
                ),
                help_text="User's full name (first + last name).",
                output_field=models.CharField(max_length=128),
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user account is active.",
                verbose_name="Active User",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user has admin privileges.",
                verbose_name="Staff User",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="User's last name.", max_length=64, verbose_name="Last Name"
            ),
        ),
    ]
