# Generated by Django 6.0.3 on 2026-04-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "name",
                    models.CharField(
                        help_text="Plný název projektu nebo iniciativy.",
                        max_length=255,
                        verbose_name="Název projektu",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unikátní URL identifikátor projektu.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailní popis projektu včetně hlavních cílů a očekávaných výsledků.",
                        verbose_name="Popis projektu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Plánovaný"),
                            ("active", "Aktivní"),
                            ("paused", "Pozastavený"),
                            ("finished", "Ukončený"),
                        ],
                        db_index=True,
                        default="planned",
                        help_text="Aktuální stav projektu.",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum zahájení projektu.",
                        null=True,
                        verbose_name="Datum začátku",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Plánované nebo skutečné datum ukončení projektu.",
                        null=True,
                        verbose_name="Datum ukončení",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Určuje, zda může být projekt zobrazen veřejně na webu.",
                        verbose_name="Veřejný",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k projektu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="Člen odpovědný za vedení a koordinaci projektu.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_projects",
                        to="members.memberprofile",
                        verbose_name="Koordinátor projektu",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Druhy, kterých se projekt týká.",
                        related_name="projects",
                        to="taxonomy.species",
                        verbose_name="Související druhy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Rok účasti v projektu.",
                        verbose_name="Rok",
                    ),
                ),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Roční poplatek za účast v projektu pro daný rok.",
                        max_digits=8,
                        verbose_name="Roční poplatek",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Určuje, zda byl poplatek uhrazen.",
                        verbose_name="Zaplaceno",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas, kdy byla platba provedena.",
                        null=True,
                        verbose_name="Datum platby",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k účasti člena v projektu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Člen zapojený do projektu.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="members.memberprofile",
                        verbose_name="Člen",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Projekt, ke kterému člen patří.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Účast v projektu",
                "verbose_name_plural": "Účasti v projektu",
                "ordering": ["-year", "project", "member"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                help_text="Členové zapojení do projektu.",
                related_name="projects",
                through="projects.ProjectMembership",
                to="members.memberprofile",
                verbose_name="Členové projektu",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("member", "project", "year"), name="unique_member_project_year"
            ),
        ),
    ]
