# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Plný název projektu nebo iniciativy.",
                        max_length=255,
                        verbose_name="Název projektu",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unikátní URL identifikátor projektu.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailní popis projektu včetně hlavních cílů a očekávaných výsledků.",
                        verbose_name="Popis projektu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Plánovaný"),
                            ("active", "Aktivní"),
                            ("paused", "Pozastavený"),
                            ("finished", "Ukončený"),
                        ],
                        db_index=True,
                        default="planned",
                        help_text="Aktuální stav projektu.",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Datum zahájení projektu.",
                        null=True,
                        verbose_name="Datum začátku",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Plánované nebo skutečné datum ukončení projektu.",
                        null=True,
                        verbose_name="Datum ukončení",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Určuje, zda může být projekt zobrazen veřejně na webu.",
                        verbose_name="Veřejný",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k projektu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="Člen odpovědný za vedení a koordinaci projektu.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_projects",
                        to="members.memberprofile",
                        verbose_name="Koordinátor projektu",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Druhy, kterých se projekt týká.",
                        related_name="projects",
                        to="taxonomy.species",
                        verbose_name="Související druhy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Rok účasti v projektu.",
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="Rok",
                    ),
                ),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Roční poplatek za účast v projektu pro daný rok.",
                        max_digits=8,
                        verbose_name="Roční poplatek",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Určuje, zda byl poplatek uhrazen.",
                        verbose_name="Zaplaceno",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas, kdy byla platba provedena.",
                        null=True,
                        verbose_name="Datum platby",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k účasti člena v projektu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Člen zapojený do projektu.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="members.memberprofile",
                        verbose_name="Člen",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Projekt, ke kterému člen patří.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                        verbose_name="Projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Účast v projektu",
                "verbose_name_plural": "Účasti v projektu",
                "ordering": ["-year", "project", "member"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                help_text="Členové zapojení do projektu.",
                related_name="projects",
                through="projects.ProjectMembership",
                to="members.memberprofile",
                verbose_name="Členové projektu",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["year"], name="projects_pr_year_c32771_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["is_paid"], name="projects_pr_is_paid_20c4cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("member", "project", "year"), name="unique_member_project_year"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date"], name="projects_pr_start_d_9f6d89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public"], name="projects_pr_is_publ_f3bb9d_idx"
            ),
        ),
    ]
