# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0003_alter_memberprofile_city_alter_memberprofile_country_and_more",
        ),
        ("projects", "0001_initial"),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Plánované nebo skutečné datum ukončení projektu.",
                null=True,
                verbose_name="Datum ukončení",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Určuje, zda může být projekt zobrazen veřejně na webu.",
                verbose_name="Veřejný",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Plný název projektu nebo iniciativy.",
                max_length=255,
                verbose_name="Název projektu",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Datum zahájení projektu.",
                null=True,
                verbose_name="Datum začátku",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Rok účasti v projektu.",
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name="Rok",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date"], name="projects_pr_start_d_9f6d89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public"], name="projects_pr_is_publ_f3bb9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["year"], name="projects_pr_year_c32771_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["is_paid"], name="projects_pr_is_paid_20c4cd_idx"
            ),
        ),
    ]
