# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Rok, pro který je výkaz chovu veden.",
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="Rok",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rozpracováno"),
                            ("submitted", "Odesláno"),
                            ("approved", "Schváleno"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Stav zpracování výkazu chovu.",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas odeslání výkazu členem.",
                        null=True,
                        verbose_name="Odesláno",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas schválení výkazu administrátorem.",
                        null=True,
                        verbose_name="Schváleno",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Uložené jméno člena v době odeslání výkazu.",
                        max_length=255,
                        verbose_name="Jméno a příjmení",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Uložená adresa člena v době odeslání výkazu.",
                        max_length=255,
                        verbose_name="Adresa",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Uložené město člena v době odeslání výkazu.",
                        max_length=150,
                        verbose_name="Město",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Uložené PSČ člena v době odeslání výkazu.",
                        max_length=50,
                        verbose_name="PSČ",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Uložená země člena v době odeslání výkazu.",
                        max_length=150,
                        verbose_name="Země",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Uložený telefon člena v době odeslání výkazu.",
                        max_length=50,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Uložený e-mail člena v době odeslání výkazu.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k výkazu jako celku.",
                        verbose_name="Poznámky",
                    ),
                ),
            ],
            options={
                "verbose_name": "Výkaz chovu",
                "verbose_name_plural": "Výkazy chovu",
                "ordering": ["-year", "member"],
            },
        ),
        migrations.CreateModel(
            name="BreedingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "pairs_with_chicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet párů, které v daném roce úspěšně odchovaly mláďata.",
                        verbose_name="Páry s odchovem",
                    ),
                ),
                (
                    "number_of_males",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet dospělých samců chovaného druhu.",
                        verbose_name="Počet samců",
                    ),
                ),
                (
                    "number_of_females",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet dospělých samic chovaného druhu.",
                        verbose_name="Počet samic",
                    ),
                ),
                (
                    "number_of_male_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných samců v daném roce.",
                        verbose_name="Počet samců odchovu",
                    ),
                ),
                (
                    "number_of_female_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných samic v daném roce.",
                        verbose_name="Počet samic odchovu",
                    ),
                ),
                (
                    "number_of_unsexed_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných kusů neurčeného pohlaví.",
                        verbose_name="Neurčený odchov",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Dodatečné interní poznámky k chovu, odchovu nebo stavu populace.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="Druh, který člen v daném roce chová.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_records",
                        to="taxonomy.species",
                        verbose_name="Druh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Záznam chovu",
                "verbose_name_plural": "Záznamy chovu",
                "ordering": ["species__latin_name"],
            },
        ),
    ]
