# Generated by Django 6.0.3 on 2026-04-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Rok, pro který je výkaz chovu veden.",
                        verbose_name="Rok",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rozpracováno"),
                            ("submitted", "Odesláno"),
                            ("approved", "Schváleno"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Stav zpracování výkazu chovu.",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas odeslání výkazu členem.",
                        null=True,
                        verbose_name="Odesláno",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum a čas schválení výkazu administrátorem.",
                        null=True,
                        verbose_name="Schváleno",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Uložené jméno člena v době odeslání výkazu.",
                        max_length=255,
                        verbose_name="Jméno a příjmení",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Uložená adresa člena v době odeslání výkazu.",
                        max_length=255,
                        verbose_name="Adresa",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Uložené město člena v době odeslání výkazu.",
                        max_length=150,
                        verbose_name="Město",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Uložené PSČ člena v době odeslání výkazu.",
                        max_length=50,
                        verbose_name="PSČ",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Uložená země člena v době odeslání výkazu.",
                        max_length=150,
                        verbose_name="Země",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Uložený telefon člena v době odeslání výkazu.",
                        max_length=50,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Uložený e-mail člena v době odeslání výkazu.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky k výkazu jako celku.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Člen organizace, ke kterému patří tento roční výkaz chovu.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_reports",
                        to="members.memberprofile",
                        verbose_name="Člen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Výkaz chovu",
                "verbose_name_plural": "Výkazy chovu",
                "ordering": ["-year", "member"],
            },
        ),
        migrations.CreateModel(
            name="BreedingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "pairs_with_chicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet párů, které v daném roce úspěšně odchovaly mláďata.",
                        verbose_name="Páry s odchovem",
                    ),
                ),
                (
                    "number_of_males",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet dospělých samců chovaného druhu.",
                        verbose_name="Počet samců",
                    ),
                ),
                (
                    "number_of_females",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet dospělých samic chovaného druhu.",
                        verbose_name="Počet samic",
                    ),
                ),
                (
                    "number_of_male_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných samců v daném roce.",
                        verbose_name="Počet samců odchovu",
                    ),
                ),
                (
                    "number_of_female_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných samic v daném roce.",
                        verbose_name="Počet samic odchovu",
                    ),
                ),
                (
                    "number_of_unsexed_offspring",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Počet odchovaných kusů neurčeného pohlaví.",
                        verbose_name="Neurčený odchov",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Dodatečné interní poznámky k chovu, odchovu nebo stavu populace.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="Druh, který člen v daném roce chová.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_records",
                        to="taxonomy.species",
                        verbose_name="Druh",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Výkaz chovu, do kterého tento řádek patří.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="breeding.breedingreport",
                        verbose_name="Výkaz chovu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Záznam chovu",
                "verbose_name_plural": "Záznamy chovu",
                "ordering": ["species__latin_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="breedingreport",
            constraint=models.UniqueConstraint(
                fields=("member", "year"), name="unique_member_year_breeding_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="breedingrecord",
            constraint=models.UniqueConstraint(
                fields=("report", "species"),
                name="unique_report_species_breeding_record",
            ),
        ),
    ]
