# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0001_initial"),
        (
            "members",
            "0003_alter_memberprofile_city_alter_memberprofile_country_and_more",
        ),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breedingrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="breedingrecord",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="breedingrecord",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="breedingrecord",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="breedingrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="breedingreport",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Rok, pro který je výkaz chovu veden.",
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name="Rok",
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["species"], name="breeding_br_species_dfb02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["report"], name="breeding_br_report__f64071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(fields=["year"], name="breeding_br_year_02dbac_idx"),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(fields=["status"], name="breeding_br_status_147be0_idx"),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(
                fields=["member"], name="breeding_br_member__d83fdc_idx"
            ),
        ),
    ]
