# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("breeding", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedingreport",
            name="member",
            field=models.ForeignKey(
                help_text="Člen organizace, ke kterému patří tento roční výkaz chovu.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeding_reports",
                to="members.memberprofile",
                verbose_name="Člen",
            ),
        ),
        migrations.AddField(
            model_name="breedingrecord",
            name="report",
            field=models.ForeignKey(
                help_text="Výkaz chovu, do kterého tento řádek patří.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="breeding.breedingreport",
                verbose_name="Výkaz chovu",
            ),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(fields=["year"], name="breeding_br_year_02dbac_idx"),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(fields=["status"], name="breeding_br_status_147be0_idx"),
        ),
        migrations.AddIndex(
            model_name="breedingreport",
            index=models.Index(
                fields=["member"], name="breeding_br_member__d83fdc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="breedingreport",
            constraint=models.UniqueConstraint(
                fields=("member", "year"), name="unique_member_year_breeding_report"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["species"], name="breeding_br_species_dfb02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["report"], name="breeding_br_report__f64071_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="breedingrecord",
            constraint=models.UniqueConstraint(
                fields=("report", "species"),
                name="unique_report_species_breeding_record",
            ),
        ),
    ]
