# Generated by Django 6.0.3 on 2026-04-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirdRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Volitelné jméno nebo interní označení jedince.",
                        max_length=150,
                        verbose_name="Jméno / označení",
                    ),
                ),
                (
                    "ring_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Jedinečné číslo kroužku, pokud je známé.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Číslo kroužku",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Samec"),
                            ("female", "Samice"),
                            ("unknown", "Neurčeno"),
                        ],
                        default="unknown",
                        help_text="Pohlaví jedince.",
                        max_length=20,
                        verbose_name="Pohlaví",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktivní"),
                            ("sold", "Prodán"),
                            ("gifted", "Darován"),
                            ("loaned", "Zapůjčen"),
                            ("deceased", "Uhynul"),
                            ("missing", "Neznámý"),
                            ("archived", "Archivován"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Aktuální stav jedince v evidenci.",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "hatch_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum vylíhnutí nebo narození jedince, pokud je známé.",
                        null=True,
                        verbose_name="Datum vylíhnutí / narození",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum, kdy byl jedinec získán do chovu.",
                        null=True,
                        verbose_name="Datum získání",
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum úhynu nebo vyřazení jedince, pokud nastalo.",
                        null=True,
                        verbose_name="Datum úhynu",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Odkud jedinec pochází, například vlastní odchov, nákup, dar nebo výměna.",
                        max_length=255,
                        verbose_name="Původ / zdroj",
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        help_text="Voliéra, farma, chovné zařízení nebo jiné aktuální umístění jedince.",
                        max_length=255,
                        verbose_name="Aktuální umístění",
                    ),
                ),
                (
                    "breeder_name",
                    models.CharField(
                        blank=True,
                        help_text="Jméno původního chovatele nebo organizace, pokud je známé.",
                        max_length=255,
                        verbose_name="Chovatel původu",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Obecné interní poznámky k jedinci.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        help_text="Otec evidovaného jedince, pokud je známý.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_from_father",
                        to="studbook.birdrecord",
                        verbose_name="Otec",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Člen organizace, kterému je jedinec aktuálně přiřazen.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birds",
                        to="members.memberprofile",
                        verbose_name="Člen",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matka evidovaného jedince, pokud je známá.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_from_mother",
                        to="studbook.birdrecord",
                        verbose_name="Matka",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="Druh evidovaného jedince.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birds",
                        to="taxonomy.species",
                        verbose_name="Druh",
                    ),
                ),
                (
                    "subspecies",
                    models.ForeignKey(
                        blank=True,
                        help_text="Poddruh evidovaného jedince, pokud je známý.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birds",
                        to="taxonomy.subspecies",
                        verbose_name="Poddruh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jedinec",
                "verbose_name_plural": "Jedinci",
                "ordering": ["species__latin_name", "ring_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="BirdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("note", "Poznámka"),
                            ("birth", "Vylíhnutí / narození"),
                            ("transfer", "Přesun / převod"),
                            ("sale", "Prodej"),
                            ("gift", "Darování"),
                            ("death", "Úhyn"),
                            ("observation", "Pozorování"),
                            ("breeding", "Chovná událost"),
                        ],
                        db_index=True,
                        default="note",
                        help_text="Typ záznamu v životní historii jedince.",
                        max_length=20,
                        verbose_name="Typ události",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        db_index=True,
                        help_text="Datum, kdy událost nastala.",
                        verbose_name="Datum události",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Krátký nadpis záznamu, například Prodej, Pozorování nebo Přesun.",
                        max_length=255,
                        verbose_name="Název události",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailní popis události.",
                        verbose_name="Popis",
                    ),
                ),
                (
                    "bird",
                    models.ForeignKey(
                        help_text="Jedinec, ke kterému se událost vztahuje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="studbook.birdrecord",
                        verbose_name="Jedinec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Událost jedince",
                "verbose_name_plural": "Události jedince",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "care_type",
                    models.CharField(
                        choices=[
                            ("feeding", "Krmení"),
                            ("deworming", "Odčervení"),
                            ("vaccination", "Vakcinace"),
                            ("supplement", "Doplněk"),
                            ("care", "Péče"),
                        ],
                        db_index=True,
                        help_text="Typ péče, například krmení, odčervení nebo vakcinace.",
                        max_length=20,
                        verbose_name="Typ péče",
                    ),
                ),
                (
                    "care_date",
                    models.DateField(
                        db_index=True,
                        help_text="Datum provedené péče.",
                        verbose_name="Datum",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        help_text="Použitý přípravek, krmivo nebo doplněk.",
                        max_length=255,
                        verbose_name="Přípravek / krmivo",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True,
                        help_text="Dávkování nebo množství, pokud je relevantní.",
                        max_length=100,
                        verbose_name="Dávkování",
                    ),
                ),
                (
                    "next_due",
                    models.DateField(
                        blank=True,
                        help_text="Datum dalšího plánovaného úkonu, pokud je známé.",
                        null=True,
                        verbose_name="Další termín",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Další interní poznámky k provedené péči.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "bird",
                    models.ForeignKey(
                        help_text="Jedinec, ke kterému se záznam péče vztahuje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_records",
                        to="studbook.birdrecord",
                        verbose_name="Jedinec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Záznam péče",
                "verbose_name_plural": "Záznamy péče",
                "ordering": ["-care_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_date",
                    models.DateField(
                        db_index=True,
                        help_text="Datum vyšetření, léčby nebo zdravotní události.",
                        verbose_name="Datum záznamu",
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        help_text="Diagnóza nebo stručné označení zdravotního problému.",
                        max_length=255,
                        verbose_name="Diagnóza",
                    ),
                ),
                (
                    "treatment",
                    models.TextField(
                        blank=True,
                        help_text="Použitá léčba, léky nebo doporučený postup.",
                        verbose_name="Léčba",
                    ),
                ),
                (
                    "veterinarian",
                    models.CharField(
                        blank=True,
                        help_text="Jméno veterináře nebo pracoviště, pokud je známé.",
                        max_length=255,
                        verbose_name="Veterinář",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Další interní poznámky ke zdravotnímu záznamu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "bird",
                    models.ForeignKey(
                        help_text="Jedinec, ke kterému se zdravotní záznam vztahuje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="studbook.birdrecord",
                        verbose_name="Jedinec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdravotní záznam",
                "verbose_name_plural": "Zdravotní záznamy",
                "ordering": ["-record_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("sale", "Prodej"),
                            ("gift", "Darování"),
                            ("exchange", "Výměna"),
                            ("move", "Přesun"),
                            ("loan", "Zapůjčení"),
                            ("return", "Vrácení"),
                        ],
                        db_index=True,
                        help_text="Typ převodu nebo přesunu jedince.",
                        max_length=20,
                        verbose_name="Typ převodu",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(
                        db_index=True,
                        help_text="Datum, kdy k převodu nebo přesunu došlo.",
                        verbose_name="Datum převodu",
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True,
                        help_text="Jméno osoby, organizace nebo chovatele, ke kterému jedinec směřuje nebo od kterého přišel.",
                        max_length=255,
                        verbose_name="Protistrana",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Místo nebo lokalita spojená s převodem či přesunem.",
                        max_length=255,
                        verbose_name="Místo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cena převodu nebo prodeje, pokud je relevantní.",
                        max_digits=10,
                        null=True,
                        verbose_name="Cena",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Další interní poznámky k převodu nebo přesunu.",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "bird",
                    models.ForeignKey(
                        help_text="Jedinec, kterého se převod nebo přesun týká.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_records",
                        to="studbook.birdrecord",
                        verbose_name="Jedinec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Záznam převodu",
                "verbose_name_plural": "Záznamy převodů",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
    ]
