# Generated by Django 6.0.3 on 2026-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0003_alter_memberprofile_city_alter_memberprofile_country_and_more",
        ),
        ("studbook", "0001_initial"),
        ("taxonomy", "0002_alter_family_latin_name_alter_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birdevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="birdevent",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="birdrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="birdrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="transferrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="transferrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AddIndex(
            model_name="birdevent",
            index=models.Index(
                fields=["event_type"], name="studbook_bi_event_t_6ccfaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdevent",
            index=models.Index(
                fields=["event_date"], name="studbook_bi_event_d_9fbd49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdrecord",
            index=models.Index(
                fields=["species"], name="studbook_bi_species_cfdc45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdrecord",
            index=models.Index(
                fields=["member"], name="studbook_bi_member__c35973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="birdrecord",
            index=models.Index(fields=["status"], name="studbook_bi_status_d874f9_idx"),
        ),
        migrations.AddIndex(
            model_name="birdrecord",
            index=models.Index(
                fields=["ring_number"], name="studbook_bi_ring_nu_934f2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carerecord",
            index=models.Index(
                fields=["care_type"], name="studbook_ca_care_ty_a2f3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carerecord",
            index=models.Index(
                fields=["care_date"], name="studbook_ca_care_da_9f3c65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthrecord",
            index=models.Index(
                fields=["record_date"], name="studbook_he_record__912aff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transferrecord",
            index=models.Index(
                fields=["transfer_type"], name="studbook_tr_transfe_8008ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transferrecord",
            index=models.Index(
                fields=["transfer_date"], name="studbook_tr_transfe_ac9711_idx"
            ),
        ),
    ]
