# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Název čeledi",
                        max_length=100,
                        verbose_name="Název",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Latinský název čeledi",
                        max_length=100,
                        verbose_name="Latinský název",
                    ),
                ),
            ],
            options={
                "verbose_name": "Čeľaď",
                "verbose_name_plural": "Čeľade",
                "ordering": ["latin_name"],
                "indexes": [
                    models.Index(
                        fields=["latin_name"], name="taxonomy_fa_latin_n_d5b6fb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Název rodu",
                        max_length=100,
                        verbose_name="Název",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Latinský název rodu",
                        max_length=100,
                        verbose_name="Latinský název",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Nadřazená čeľaď",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genera",
                        to="taxonomy.family",
                        verbose_name="Čeľaď",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rod",
                "verbose_name_plural": "Rody",
                "ordering": ["latin_name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední úpravy",
                        verbose_name="Upraveno",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Titulek pro SEO (HTML <title>)",
                        max_length=255,
                        verbose_name="Meta titulek",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Krátký popis pro vyhledávače",
                        verbose_name="Meta popis",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Klíčová slova oddělená čárkou",
                        max_length=255,
                        verbose_name="Meta klíčová slova",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Latinský název druhu",
                        max_length=150,
                        verbose_name="Latinský název",
                    ),
                ),
                (
                    "czech_name",
                    models.CharField(
                        db_index=True,
                        help_text="Český název druhu",
                        max_length=150,
                        verbose_name="Český název",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        help_text="Autor vědeckého názvu",
                        max_length=100,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Zda je druh aktivně používán",
                        verbose_name="Aktivní",
                    ),
                ),
                (
                    "subspecies_note",
                    models.TextField(
                        blank=True,
                        help_text="Poznámky k poddruhům",
                        verbose_name="Poznámka poddruhů",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Doplňující informace o druhu",
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "distribution",
                    models.TextField(
                        blank=True,
                        help_text="Geografické rozšíření druhu",
                        verbose_name="Rozšíření",
                    ),
                ),
                (
                    "habitat",
                    models.TextField(
                        blank=True,
                        help_text="Typy biotopu, kde druh žije",
                        verbose_name="Biotop",
                    ),
                ),
                (
                    "status_in_nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "Málo dotknutý"),
                            ("NT", "Takmer ohrozený"),
                            ("VU", "Zraniteľný"),
                            ("EN", "Ohrozený"),
                            ("CR", "Kriticky ohrozený"),
                        ],
                        db_index=True,
                        help_text="Ochranný status dle IUCN",
                        max_length=10,
                        verbose_name="Stav v přírodě",
                    ),
                ),
                (
                    "status_in_captivity",
                    models.TextField(
                        blank=True,
                        help_text="Informace o chovu v zajetí",
                        verbose_name="Stav v zajetí",
                    ),
                ),
                (
                    "maturity",
                    models.CharField(
                        blank=True,
                        help_text="Doba dosažení pohlavní dospělosti",
                        max_length=50,
                        verbose_name="Dospělost",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        blank=True,
                        help_text="Průměrná délka jedince",
                        max_length=50,
                        verbose_name="Délka",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="Průměrná hmotnost jedince",
                        max_length=50,
                        verbose_name="Hmotnost",
                    ),
                ),
                (
                    "clutch",
                    models.CharField(
                        blank=True,
                        help_text="Počet vajec ve snůšce",
                        max_length=50,
                        verbose_name="Snůška",
                    ),
                ),
                (
                    "incubation",
                    models.CharField(
                        blank=True,
                        help_text="Doba inkubace vajec",
                        max_length=50,
                        verbose_name="Inkubační doba",
                    ),
                ),
                (
                    "ring_size",
                    models.FloatField(
                        blank=True,
                        help_text="Velikost identifikačního kroužku v mm",
                        null=True,
                        verbose_name="Velikost kroužku",
                    ),
                ),
                (
                    "population",
                    models.TextField(
                        blank=True, help_text="Odhad populace", verbose_name="Populace"
                    ),
                ),
                (
                    "breeding_difficulty",
                    models.TextField(
                        blank=True,
                        help_text="Náročnost chovu",
                        verbose_name="Obtížnost chovu",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hlavní obrázek druhu",
                        null=True,
                        upload_to="taxonomy/species/",
                        verbose_name="Hlavní obrázek",
                    ),
                ),
                (
                    "secondary_image",
                    models.ImageField(
                        blank=True,
                        help_text="Doplňkový obrázek druhu",
                        null=True,
                        upload_to="taxonomy/species/",
                        verbose_name="Doplňkový obrázek",
                    ),
                ),
                (
                    "videos",
                    models.TextField(
                        blank=True,
                        help_text="YouTube odkazy (1 na řádek)",
                        verbose_name="Videa",
                    ),
                ),
                (
                    "images_url",
                    models.URLField(
                        blank=True,
                        help_text="Odkaz na album na Facebooku",
                        verbose_name="URL obrázků",
                    ),
                ),
                (
                    "genus",
                    models.ForeignKey(
                        help_text="Rod, do kterého druh patří",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="taxonomy.genus",
                        verbose_name="Rod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Druh",
                "verbose_name_plural": "Druhy",
                "ordering": ["latin_name"],
            },
        ),
        migrations.CreateModel(
            name="Subspecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Latinský název poddruhu",
                        max_length=150,
                        verbose_name="Latinský název",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Doplňující informace",
                        verbose_name="Poznámka",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        blank=True,
                        help_text="Specifická délka pro poddruh",
                        max_length=50,
                        verbose_name="Délka",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="Nadřazený druh",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subspecies",
                        to="taxonomy.species",
                        verbose_name="Druh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poddruh",
                "verbose_name_plural": "Poddruhy",
                "ordering": ["latin_name"],
            },
        ),
        migrations.AddIndex(
            model_name="genus",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_ge_latin_n_4c91d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genus",
            index=models.Index(
                fields=["family"], name="taxonomy_ge_family__af0be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_sp_latin_n_9537b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["czech_name"], name="taxonomy_sp_czech_n_b74848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["is_active"], name="taxonomy_sp_is_acti_15418e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subspecies",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_su_latin_n_04c5e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subspecies",
            index=models.Index(
                fields=["species"], name="taxonomy_su_species_9e89a5_idx"
            ),
        ),
    ]
