# Generated by Django 6.0.3 on 2026-04-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("latin_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Čeľaď",
                "verbose_name_plural": "Čeľade",
                "ordering": ["latin_name"],
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("latin_name", models.CharField(max_length=100)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genera",
                        to="taxonomy.family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rod",
                "verbose_name_plural": "Rody",
                "ordering": ["latin_name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("latin_name", models.CharField(max_length=150)),
                ("czech_name", models.CharField(max_length=150)),
                ("authority", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("subspecies_note", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("distribution", models.TextField(blank=True)),
                ("habitat", models.TextField(blank=True)),
                (
                    "status_in_nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "Málo dotknutý"),
                            ("NT", "Takmer ohrozený"),
                            ("VU", "Zraniteľný"),
                            ("EN", "Ohrozený"),
                            ("CR", "Kriticky ohrozený"),
                        ],
                        max_length=10,
                    ),
                ),
                ("status_in_captivity", models.TextField(blank=True)),
                ("maturity", models.CharField(blank=True, max_length=50)),
                ("length", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                ("clutch", models.CharField(blank=True, max_length=50)),
                ("incubation", models.CharField(blank=True, max_length=50)),
                ("ring_size", models.FloatField(blank=True, null=True)),
                ("population", models.TextField(blank=True)),
                ("breeding_difficulty", models.TextField(blank=True)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="taxonomy/species/"
                    ),
                ),
                (
                    "secondary_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="taxonomy/species/"
                    ),
                ),
                ("videos", models.TextField(blank=True)),
                ("images_url", models.URLField(blank=True)),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="taxonomy.genus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Druh",
                "verbose_name_plural": "Druhy",
                "ordering": ["latin_name"],
            },
        ),
        migrations.CreateModel(
            name="Subspecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latin_name", models.CharField(max_length=150)),
                ("note", models.TextField(blank=True)),
                ("length", models.CharField(blank=True, max_length=50)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subspecies",
                        to="taxonomy.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poddruh",
                "verbose_name_plural": "Poddruhy",
                "ordering": ["latin_name"],
            },
        ),
    ]
