# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="latin_name",
            field=models.CharField(
                db_index=True,
                help_text="Latinský název čeledi",
                max_length=100,
                verbose_name="Latinský název",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Název čeledi",
                max_length=100,
                verbose_name="Název",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="family",
            field=models.ForeignKey(
                help_text="Nadřazená čeľaď",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genera",
                to="taxonomy.family",
                verbose_name="Čeľaď",
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="latin_name",
            field=models.CharField(
                db_index=True,
                help_text="Latinský název rodu",
                max_length=100,
                verbose_name="Latinský název",
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Název rodu",
                max_length=100,
                verbose_name="Název",
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="authority",
            field=models.CharField(
                blank=True,
                help_text="Autor vědeckého názvu",
                max_length=100,
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="breeding_difficulty",
            field=models.TextField(
                blank=True, help_text="Náročnost chovu", verbose_name="Obtížnost chovu"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="clutch",
            field=models.CharField(
                blank=True,
                help_text="Počet vajec ve snůšce",
                max_length=50,
                verbose_name="Snůška",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="czech_name",
            field=models.CharField(
                db_index=True,
                help_text="Český název druhu",
                max_length=150,
                verbose_name="Český název",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="distribution",
            field=models.TextField(
                blank=True,
                help_text="Geografické rozšíření druhu",
                verbose_name="Rozšíření",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                help_text="Rod, do kterého druh patří",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species",
                to="taxonomy.genus",
                verbose_name="Rod",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="habitat",
            field=models.TextField(
                blank=True,
                help_text="Typy biotopu, kde druh žije",
                verbose_name="Biotop",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="images_url",
            field=models.URLField(
                blank=True,
                help_text="Odkaz na album na Facebooku",
                verbose_name="URL obrázků",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="incubation",
            field=models.CharField(
                blank=True,
                help_text="Doba inkubace vajec",
                max_length=50,
                verbose_name="Inkubační doba",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Zda je druh aktivně používán",
                verbose_name="Aktivní",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="latin_name",
            field=models.CharField(
                db_index=True,
                help_text="Latinský název druhu",
                max_length=150,
                verbose_name="Latinský název",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="length",
            field=models.CharField(
                blank=True,
                help_text="Průměrná délka jedince",
                max_length=50,
                verbose_name="Délka",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Hlavní obrázek druhu",
                null=True,
                upload_to="taxonomy/species/",
                verbose_name="Hlavní obrázek",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="maturity",
            field=models.CharField(
                blank=True,
                help_text="Doba dosažení pohlavní dospělosti",
                max_length=50,
                verbose_name="Dospělost",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Krátký popis pro vyhledávače",
                verbose_name="Meta popis",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Klíčová slova oddělená čárkou",
                max_length=255,
                verbose_name="Meta klíčová slova",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Titulek pro SEO (HTML <title>)",
                max_length=255,
                verbose_name="Meta titulek",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Doplňující informace o druhu",
                verbose_name="Poznámky",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="population",
            field=models.TextField(
                blank=True, help_text="Odhad populace", verbose_name="Populace"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="ring_size",
            field=models.FloatField(
                blank=True,
                help_text="Velikost identifikačního kroužku v mm",
                null=True,
                verbose_name="Velikost kroužku",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="secondary_image",
            field=models.ImageField(
                blank=True,
                help_text="Doplňkový obrázek druhu",
                null=True,
                upload_to="taxonomy/species/",
                verbose_name="Doplňkový obrázek",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="status_in_captivity",
            field=models.TextField(
                blank=True,
                help_text="Informace o chovu v zajetí",
                verbose_name="Stav v zajetí",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="status_in_nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LC", "Málo dotknutý"),
                    ("NT", "Takmer ohrozený"),
                    ("VU", "Zraniteľný"),
                    ("EN", "Ohrozený"),
                    ("CR", "Kriticky ohrozený"),
                ],
                db_index=True,
                help_text="Ochranný status dle IUCN",
                max_length=10,
                verbose_name="Stav v přírodě",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="subspecies_note",
            field=models.TextField(
                blank=True,
                help_text="Poznámky k poddruhům",
                verbose_name="Poznámka poddruhů",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední úpravy",
                verbose_name="Upraveno",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="videos",
            field=models.TextField(
                blank=True,
                help_text="YouTube odkazy (1 na řádek)",
                verbose_name="Videa",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight",
            field=models.CharField(
                blank=True,
                help_text="Průměrná hmotnost jedince",
                max_length=50,
                verbose_name="Hmotnost",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="latin_name",
            field=models.CharField(
                db_index=True,
                help_text="Latinský název poddruhu",
                max_length=150,
                verbose_name="Latinský název",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="length",
            field=models.CharField(
                blank=True,
                help_text="Specifická délka pro poddruh",
                max_length=50,
                verbose_name="Délka",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="note",
            field=models.TextField(
                blank=True, help_text="Doplňující informace", verbose_name="Poznámka"
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="species",
            field=models.ForeignKey(
                help_text="Nadřazený druh",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subspecies",
                to="taxonomy.species",
                verbose_name="Druh",
            ),
        ),
        migrations.AddIndex(
            model_name="family",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_fa_latin_n_d5b6fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genus",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_ge_latin_n_4c91d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genus",
            index=models.Index(
                fields=["family"], name="taxonomy_ge_family__af0be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_sp_latin_n_9537b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["czech_name"], name="taxonomy_sp_czech_n_b74848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["is_active"], name="taxonomy_sp_is_acti_15418e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subspecies",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_su_latin_n_04c5e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subspecies",
            index=models.Index(
                fields=["species"], name="taxonomy_su_species_9e89a5_idx"
            ),
        ),
    ]
