# Generated by Django 6.0.3 on 2026-04-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("yt", "YouTube"), ("fb", "Facebook")],
                        help_text="Typ odkazu",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Odkaz na video nebo album", verbose_name="URL"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Volitelný název odkazu (např. Tokání samce)",
                        max_length=200,
                        verbose_name="Název",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odkaz",
                "verbose_name_plural": "Odkazy",
                "ordering": ["type"],
            },
        ),
        migrations.RemoveField(
            model_name="species",
            name="clutch",
        ),
        migrations.RemoveField(
            model_name="species",
            name="images_url",
        ),
        migrations.RemoveField(
            model_name="species",
            name="incubation",
        ),
        migrations.RemoveField(
            model_name="species",
            name="length",
        ),
        migrations.RemoveField(
            model_name="species",
            name="secondary_image",
        ),
        migrations.RemoveField(
            model_name="species",
            name="videos",
        ),
        migrations.RemoveField(
            model_name="species",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="subspecies",
            name="length",
        ),
        migrations.RemoveField(
            model_name="subspecies",
            name="note",
        ),
        migrations.AddField(
            model_name="family",
            name="czech_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Český název čeledi",
                max_length=100,
                verbose_name="Český název",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="english_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anglický název čeledi",
                max_length=100,
                verbose_name="Anglický název",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="german_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Německý název čeledi",
                max_length=100,
                verbose_name="Německý název",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="slovak_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Slovenský názov čeledi",
                max_length=100,
                verbose_name="Slovenský názov",
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="czech_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Český název rodu",
                max_length=100,
                verbose_name="Český název",
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="english_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anglický název rodu",
                max_length=100,
                verbose_name="Anglický název",
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="german_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Německý název rodu",
                max_length=100,
                verbose_name="Německý název",
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="slovak_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Slovenský názov rodu",
                max_length=100,
                verbose_name="Slovenský názov",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="authority_year",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Rok, kdy byl druh vědecky popsán",
                null=True,
                verbose_name="Rok popisu",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="clutch_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální počet vajec ve snůšce",
                null=True,
                verbose_name="Snůška (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="clutch_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální počet vajec ve snůšce",
                null=True,
                verbose_name="Snůška (min)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="clutch_note",
            field=models.CharField(
                blank=True,
                help_text="Doplňující informace (např. konec dubna apod.)",
                max_length=100,
                verbose_name="Snůška – poznámka",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="english_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anglický název druhu",
                max_length=150,
                verbose_name="Anglický název",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="german_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Německý název druhu",
                max_length=150,
                verbose_name="Německý název",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="incubation_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální doba inkubace ve dnech",
                null=True,
                verbose_name="Inkubace (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="incubation_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální doba inkubace ve dnech",
                null=True,
                verbose_name="Inkubace (min)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="incubation_note",
            field=models.CharField(
                blank=True,
                help_text="Doplňující informace (např. závislost na podmínkách apod.)",
                max_length=100,
                verbose_name="Inkubace – poznámka",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="length_female_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální délka samice v cm",
                null=True,
                verbose_name="Délka samice (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="length_female_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální délka samice v cm",
                null=True,
                verbose_name="Délka samice (min)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="length_male_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální délka samce v cm",
                null=True,
                verbose_name="Délka samec (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="length_male_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální délka samce v cm",
                null=True,
                verbose_name="Délka samec (min)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="slovak_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Slovenský názov druhu",
                max_length=150,
                verbose_name="Slovenský názov",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="weight_female_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální hmotnost samice v g",
                null=True,
                verbose_name="Hmotnost samice (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="weight_female_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální hmotnost samice v g",
                null=True,
                verbose_name="Hmotnost samice (min)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="weight_male_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální hmotnost samce v g",
                null=True,
                verbose_name="Hmotnost samec (max)",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="weight_male_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální hmotnost samce v g",
                null=True,
                verbose_name="Hmotnost samec (min)",
            ),
        ),
        migrations.AddField(
            model_name="subspecies",
            name="czech_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Český název poddruhu",
                max_length=150,
                verbose_name="Český název",
            ),
        ),
        migrations.AddField(
            model_name="subspecies",
            name="english_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anglický název poddruhu",
                max_length=150,
                verbose_name="Anglický název",
            ),
        ),
        migrations.AddField(
            model_name="subspecies",
            name="german_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Německý název poddruhu",
                max_length=150,
                verbose_name="Německý název",
            ),
        ),
        migrations.AddField(
            model_name="subspecies",
            name="slovak_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Slovenský název poddruhu",
                max_length=150,
                verbose_name="Slovenský názov",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="breeding_difficulty",
            field=models.CharField(
                blank=True,
                help_text="Náročnost chovu",
                max_length=100,
                verbose_name="Obtížnost chovu",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="distribution",
            field=models.TextField(
                blank=True,
                help_text="Geografické rozšíření druhu",
                verbose_name="Výskyt",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="habitat",
            field=models.TextField(
                blank=True,
                help_text="Typy biotopu, kde druh žije",
                verbose_name="Obývá",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="population",
            field=models.TextField(
                blank=True,
                help_text="Odhad populace v ČR a SR",
                verbose_name="Populace (CZ/SK)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="ring_size",
            field=models.IntegerField(
                blank=True,
                help_text="Velikost identifikačního kroužku v mm",
                null=True,
                verbose_name="Velikost kroužku",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="status_in_nature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LC", "Málo dotknutý"),
                    ("NT", "Takmer ohrozený"),
                    ("VU", "Zraniteľný"),
                    ("EN", "Ohrozený"),
                    ("CR", "Kriticky ohrozený"),
                    ("EW", "Vyhynutý v prírode"),
                    ("EX", "Vyhynutý"),
                ],
                db_index=True,
                help_text="Ochranný status dle IUCN",
                max_length=10,
                verbose_name="Stav v přírodě",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="subspecies_note",
            field=models.CharField(
                blank=True,
                choices=[("mono", "Monotypický"), ("poly", "Polytypický")],
                help_text="Zda je druh monotypický nebo polytypický",
                max_length=10,
                verbose_name="Typ druhu",
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["slovak_name"], name="taxonomy_sp_slovak__e6d0f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["english_name"], name="taxonomy_sp_english_72a82e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="species",
            index=models.Index(
                fields=["german_name"], name="taxonomy_sp_german__2a7cc3_idx"
            ),
        ),
        migrations.AddField(
            model_name="specieslink",
            name="species",
            field=models.ForeignKey(
                help_text="Přiřazený druh",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="taxonomy.species",
                verbose_name="Druh",
            ),
        ),
    ]
