# Generated by Django 6.0.3 on 2026-04-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_specieslink_remove_species_clutch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="name",
        ),
        migrations.RemoveField(
            model_name="genus",
            name="name",
        ),
    ]
