# Generated by Django 6.0.3 on 2026-04-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0003_remove_family_name_remove_genus_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="species",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="species",
            name="meta_title",
        ),
    ]
