# Generated by Django 6.0.3 on 2026-04-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0004_remove_species_meta_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subfamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL identifikátor (automaticky generovaný pokud není vyplněn)",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Latinský název podčeledi",
                        max_length=100,
                        verbose_name="Latinský název",
                    ),
                ),
                (
                    "czech_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Český název podčeledi",
                        max_length=100,
                        verbose_name="Český název",
                    ),
                ),
                (
                    "slovak_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Slovenský názov podčeledi",
                        max_length=100,
                        verbose_name="Slovenský názov",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Anglický název podčeledi",
                        max_length=100,
                        verbose_name="Anglický název",
                    ),
                ),
                (
                    "german_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Německý název podčeledi",
                        max_length=100,
                        verbose_name="Německý název",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Nadřazená čeľaď",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfamilies",
                        to="taxonomy.family",
                        verbose_name="Čeľaď",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podčeľaď",
                "verbose_name_plural": "Podčeľade",
                "ordering": ["latin_name"],
            },
        ),
        migrations.AddField(
            model_name="genus",
            name="subfamily",
            field=models.ForeignKey(
                blank=True,
                help_text="Podčeľaď, do které rod patří",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genera",
                to="taxonomy.subfamily",
                verbose_name="Podčeľaď",
            ),
        ),
        migrations.AddIndex(
            model_name="subfamily",
            index=models.Index(
                fields=["latin_name"], name="taxonomy_su_latin_n_175d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subfamily",
            index=models.Index(
                fields=["family"], name="taxonomy_su_family__46bef9_idx"
            ),
        ),
    ]
