# Generated by Django 6.0.3 on 2026-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0005_subfamily_genus_subfamily_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="genus",
            name="taxonomy_ge_family__af0be6_idx",
        ),
        migrations.AddIndex(
            model_name="genus",
            index=models.Index(
                fields=["subfamily"], name="taxonomy_ge_subfami_21dac9_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="genus",
            name="family",
        ),
    ]
