# Generated by Django 6.0.3 on 2026-04-19 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0006_remove_genus_taxonomy_ge_family__af0be6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="clutch_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální počet vajec ve snůšce",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Snůška (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="clutch_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální počet vajec ve snůšce",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Snůška (min)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="incubation_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální doba inkubace ve dnech",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inkubace (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="incubation_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální doba inkubace ve dnech",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inkubace (min)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="length_female_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální délka samice v cm",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Délka samice (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="length_female_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální délka samice v cm",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Délka samice (min)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="length_male_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální délka samce v cm",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Délka samec (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="length_male_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální délka samce v cm",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Délka samec (min)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="ring_size",
            field=models.IntegerField(
                blank=True,
                help_text="Velikost identifikačního kroužku v mm",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Velikost kroužku",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight_female_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální hmotnost samice v g",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hmotnost samice (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight_female_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální hmotnost samice v g",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hmotnost samice (min)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight_male_max",
            field=models.IntegerField(
                blank=True,
                help_text="Maximální hmotnost samce v g",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hmotnost samec (max)",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight_male_min",
            field=models.IntegerField(
                blank=True,
                help_text="Minimální hmotnost samce v g",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hmotnost samec (min)",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="slovak_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Slovenský názov poddruhu",
                max_length=150,
                verbose_name="Slovenský názov",
            ),
        ),
    ]
