# Generated by Django 5.2.4 on 2026-04-02 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("member", "Člen"), ("honorary", "Čestný člen")],
                        db_index=True,
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("president", "Predseda"),
                            ("vice_president", "Miestopredseda"),
                            ("treasurer", "Pokladník"),
                            ("registrar", "Registrátor"),
                            ("web_admin", "Správca webu"),
                            ("manager", "Jednateľ"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("registration_number"), nulls_last=True),
                    "created_at",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user",), name="unique_member_per_user"
                    )
                ],
            },
        ),
    ]
