# Generated by Django 6.0.3 on 2026-04-17 17:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icch_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unikátní identifikační číslo člena",
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="ICCH číslo",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("regular", "Řádné členství"),
                            ("honorary", "Čestné členství"),
                            ("junior", "Juniorské členství"),
                        ],
                        db_index=True,
                        default="regular",
                        help_text="Typ členství v organizaci",
                        max_length=20,
                        verbose_name="Typ členství",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("person", "Fyzická osoba"),
                            ("organization", "Organizace"),
                        ],
                        db_index=True,
                        default="person",
                        help_text="Určuje, zda jde o fyzickou osobu nebo organizaci (např. ZOO)",
                        max_length=20,
                        verbose_name="Typ člena",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Zda je člen aktivní",
                        verbose_name="Aktivní",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                        db_index=True,
                        default="unpaid",
                        help_text="Stav členského příspěvku",
                        max_length=20,
                        verbose_name="Stav platby",
                    ),
                ),
                (
                    "joined_at",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Datum vstupu do organizace",
                        null=True,
                        verbose_name="Datum vstupu",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Datum platnosti členství",
                        null=True,
                        verbose_name="Platnost do",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interní poznámky",
                        max_length=256,
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Kontaktní telefon",
                        max_length=24,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Město bydliště",
                        max_length=64,
                        verbose_name="Město",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Ulice",
                        max_length=128,
                        verbose_name="Ulice",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Číslo domu",
                        max_length=32,
                        verbose_name="Číslo domu",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Poštovní směrovací číslo",
                        max_length=10,
                        verbose_name="PSČ",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        help_text="Okres nebo region",
                        max_length=64,
                        verbose_name="Okres",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        db_index=True,
                        help_text="Stát (výběr ze seznamu)",
                        max_length=2,
                        verbose_name="Stát",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední aktualizace záznamu",
                        verbose_name="Aktualizováno",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("icch_number"), nulls_last=True),
                    "created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Křestní jméno", max_length=64, verbose_name="Jméno"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Příjmení", max_length=64, verbose_name="Příjmení"
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        blank=True,
                        help_text="Akademický titul",
                        max_length=48,
                        verbose_name="Titul",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Datum narození", verbose_name="Datum narození"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Město bydliště", max_length=64, verbose_name="Město"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Ulice", max_length=128, verbose_name="Ulice"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="Číslo domu", max_length=32, verbose_name="Číslo domu"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Poštovní směrovací číslo",
                        max_length=10,
                        verbose_name="PSČ",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        help_text="Okres nebo region",
                        max_length=64,
                        verbose_name="Okres",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Stát (výběr ze seznamu)",
                        max_length=2,
                        verbose_name="Stát",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Kontaktní telefon",
                        max_length=24,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Emailová adresa",
                        max_length=128,
                        verbose_name="Email",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Doplňující informace",
                        max_length=256,
                        verbose_name="Poznámky",
                    ),
                ),
                (
                    "declaration_place",
                    models.CharField(
                        help_text="Místo, kde bylo prohlášení podepsáno",
                        max_length=128,
                        verbose_name="Místo prohlášení",
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        help_text="Datum prohlášení", verbose_name="Datum prohlášení"
                    ),
                ),
                (
                    "declaration_signature",
                    models.CharField(
                        help_text="Podpis žadatele",
                        max_length=128,
                        verbose_name="Podpis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Čaká"),
                            ("approved", "Schválené"),
                            ("rejected", "Zamietnuté"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Stav žádosti",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "initial_payment_status",
                    models.CharField(
                        choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                        db_index=True,
                        default="unpaid",
                        help_text="Stav vstupního poplatku",
                        max_length=20,
                        verbose_name="Stav platby",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Datum a čas vytvoření záznamu",
                        verbose_name="Vytvořeno",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum a čas poslední aktualizace záznamu",
                        verbose_name="Aktualizováno",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Názov"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Role (funkcie)",
                "ordering": ["name"],
            },
        ),
    ]
