# Generated by Django 6.0.3 on 2026-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("member", "Člen"), ("honorary", "Čestný člen")],
                        db_index=True,
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("president", "Předseda"),
                            ("vice_president", "Místopředseda"),
                            ("treasurer", "Pokladník"),
                            ("registrar", "Registrátor"),
                            ("web_admin", "Správce webu"),
                            ("manager", "Jednatel"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=256)),
                ("phone_number", models.CharField(blank=True, max_length=24)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("street", models.CharField(blank=True, max_length=128)),
                ("house_number", models.CharField(blank=True, max_length=32)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("district", models.CharField(blank=True, max_length=64)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("registration_number"), nulls_last=True),
                    "created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("academic_title", models.CharField(blank=True, max_length=48)),
                ("birth_date", models.DateField()),
                ("city", models.CharField(max_length=64)),
                ("street", models.CharField(max_length=128)),
                ("house_number", models.CharField(max_length=32)),
                ("postal_code", models.CharField(max_length=10)),
                ("district", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=2)),
                ("phone_number", models.CharField(blank=True, max_length=24)),
                ("email", models.EmailField(db_index=True, max_length=128)),
                ("notes", models.TextField(blank=True, max_length=256)),
                ("declaration_place", models.CharField(max_length=128)),
                ("declaration_date", models.DateField()),
                ("declaration_signature", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Čaká"),
                            ("approved", "Schválené"),
                            ("rejected", "Zamietnuté"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
