# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Propojený uživatelský účet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uživatel",
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propojený uživatel (pokud existuje)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uživatel",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Funkcie člena v organizaci",
                related_name="members",
                to="members.role",
                verbose_name="Role",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(
                fields=["status", "initial_payment_status"],
                name="members_mem_status_9de056_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "approved"])),
                fields=("email",),
                name="unique_active_application_per_email",
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["membership_type"], name="members_mem_members_c68c75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["payment_status"], name="members_mem_payment_6b218d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["is_active"], name="members_mem_is_acti_95819d_idx"
            ),
        ),
    ]
