# Generated by Django 6.0.3 on 2026-04-11 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Město bydliště",
                max_length=64,
                verbose_name="Město",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Kód státu (např. CZ, SK)",
                max_length=2,
                verbose_name="Stát",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="district",
            field=models.CharField(
                blank=True,
                help_text="Okres nebo region",
                max_length=64,
                verbose_name="Okres",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="house_number",
            field=models.CharField(
                blank=True,
                help_text="Číslo domu",
                max_length=32,
                verbose_name="Číslo domu",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="icch_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unikátní identifikační číslo člena",
                max_length=4,
                null=True,
                unique=True,
                verbose_name="ICCH číslo",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Zda je člen aktivní",
                verbose_name="Aktivní",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="joined_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Datum vstupu do organizace",
                null=True,
                verbose_name="Datum vstupu",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("regular", "Řádné členství"),
                    ("honorary", "Čestné členství"),
                    ("junior", "Juniorské členství"),
                ],
                db_index=True,
                default="regular",
                help_text="Typ členství v organizaci",
                max_length=20,
                verbose_name="Typ členství",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Interní poznámky",
                max_length=256,
                verbose_name="Poznámky",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                db_index=True,
                default="unpaid",
                help_text="Stav členského příspěvku",
                max_length=20,
                verbose_name="Stav platby",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Kontaktní telefon",
                max_length=24,
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "Předseda"),
                    ("vice_president", "Místopředseda"),
                    ("treasurer", "Pokladník"),
                    ("registrar", "Registrátor"),
                    ("web_admin", "Správce webu"),
                    ("manager", "Jednatel"),
                ],
                help_text="Funkce člena v organizaci",
                max_length=24,
                null=True,
                verbose_name="Pozice",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Poštovní směrovací číslo",
                max_length=10,
                verbose_name="PSČ",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="street",
            field=models.CharField(
                blank=True, help_text="Ulice", max_length=128, verbose_name="Ulice"
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední aktualizace záznamu",
                verbose_name="Aktualizováno",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Propojený uživatelský účet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uživatel",
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="valid_until",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Datum platnosti členství",
                null=True,
                verbose_name="Platnost do",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="academic_title",
            field=models.CharField(
                blank=True,
                help_text="Akademický titul",
                max_length=48,
                verbose_name="Titul",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="birth_date",
            field=models.DateField(
                help_text="Datum narození", verbose_name="Datum narození"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="city",
            field=models.CharField(
                help_text="Město bydliště", max_length=64, verbose_name="Město"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="country",
            field=models.CharField(
                help_text="Kód státu (např. CZ, SK)", max_length=2, verbose_name="Stát"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Datum a čas vytvoření záznamu",
                verbose_name="Vytvořeno",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="declaration_date",
            field=models.DateField(
                help_text="Datum prohlášení", verbose_name="Datum prohlášení"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="declaration_place",
            field=models.CharField(
                help_text="Místo, kde bylo prohlášení podepsáno",
                max_length=128,
                verbose_name="Místo prohlášení",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="declaration_signature",
            field=models.CharField(
                help_text="Podpis žadatele", max_length=128, verbose_name="Podpis"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="district",
            field=models.CharField(
                help_text="Okres nebo region", max_length=64, verbose_name="Okres"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Emailová adresa",
                max_length=128,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="first_name",
            field=models.CharField(
                help_text="Křestní jméno", max_length=64, verbose_name="Jméno"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="house_number",
            field=models.CharField(
                help_text="Číslo domu", max_length=32, verbose_name="Číslo domu"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="initial_payment_status",
            field=models.CharField(
                choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                db_index=True,
                default="unpaid",
                help_text="Stav vstupního poplatku",
                max_length=20,
                verbose_name="Stav platby",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="last_name",
            field=models.CharField(
                help_text="Příjmení", max_length=64, verbose_name="Příjmení"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Doplňující informace",
                max_length=256,
                verbose_name="Poznámky",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Kontaktní telefon",
                max_length=24,
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="postal_code",
            field=models.CharField(
                help_text="Poštovní směrovací číslo", max_length=10, verbose_name="PSČ"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čaká"),
                    ("approved", "Schválené"),
                    ("rejected", "Zamietnuté"),
                ],
                db_index=True,
                default="pending",
                help_text="Stav žádosti",
                max_length=20,
                verbose_name="Stav",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="street",
            field=models.CharField(
                help_text="Ulice", max_length=128, verbose_name="Ulice"
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datum a čas poslední aktualizace záznamu",
                verbose_name="Aktualizováno",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Propojený uživatel (pokud existuje)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uživatel",
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["membership_type"], name="members_mem_members_c68c75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["payment_status"], name="members_mem_payment_6b218d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(
                fields=["is_active"], name="members_mem_is_acti_95819d_idx"
            ),
        ),
    ]
