# Generated by Django 6.0.3 on 2026-04-05 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberprofile",
            options={
                "ordering": [
                    models.OrderBy(models.F("icch_number"), nulls_last=True),
                    "created_at",
                ]
            },
        ),
        migrations.RemoveIndex(
            model_name="membershipapplication",
            name="members_mem_status_4fae31_idx",
        ),
        migrations.RenameField(
            model_name="membershipapplication",
            old_name="payment_status",
            new_name="initial_payment_status",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="status",
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="icch_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=4, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("regular", "Řádné členství"),
                    ("honorary", "Čestné členství"),
                    ("junior", "Juniorské členství"),
                ],
                db_index=True,
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(
                fields=["status", "initial_payment_status"],
                name="members_mem_status_9de056_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "approved"])),
                fields=("email",),
                name="unique_active_application_per_email",
            ),
        ),
    ]
