# Generated by Django 5.2.4 on 2026-04-02 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_memberprofile_registration_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="note",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("academic_title", models.CharField(blank=True, max_length=48)),
                ("birth_date", models.DateField()),
                ("city", models.CharField(max_length=64)),
                ("street", models.CharField(max_length=128)),
                ("house_number", models.CharField(max_length=32)),
                ("postal_code", models.CharField(max_length=10)),
                ("district", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=2)),
                ("phone_number", models.CharField(blank=True, max_length=24)),
                ("email", models.EmailField(max_length=128)),
                ("notes", models.TextField(blank=True, max_length=256)),
                ("declaration_place", models.CharField(max_length=128)),
                ("declaration_date", models.DateField()),
                ("declaration_signature", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Čaká"),
                            ("approved", "Schválené"),
                            ("rejected", "Zamietnuté"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Nezaplatené"), ("paid", "Zaplatené")],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
