# Generated by Django 5.2.4 on 2026-04-02 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_memberprofile_note_membershipapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="email",
            field=models.EmailField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(
                fields=["status", "payment_status"],
                name="members_mem_status_4fae31_idx",
            ),
        ),
    ]
