# Generated by Django 5.2.4 on 2026-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_membershipapplication_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="memberprofile",
            name="unique_member_per_user",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "Předseda"),
                    ("vice_president", "Místopředseda"),
                    ("treasurer", "Pokladník"),
                    ("registrar", "Registrátor"),
                    ("web_admin", "Správce webu"),
                    ("manager", "Jednatel"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="registration_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, null=True, unique=True
            ),
        ),
    ]
