# Generated by Django 5.2.4 on 2026-04-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_remove_memberprofile_unique_member_per_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberprofile",
            old_name="note",
            new_name="notes",
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="district",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="house_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="street",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
